import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// Extended product database with 50+ products across categories
const products = [
  // Beverages - Sodas
  {
    upc: '012000161551',
    brand: 'Coca-Cola',
    name: 'Coca-Cola Classic',
    description: 'Carbonated soft drink',
    servingSize: '12 fl oz (355mL)',
    calories: 140,
    totalSugars: 39,
    addedSugars: 39,
    totalCarbs: 39,
    protein: 0,
    fat: 0,
    sodium: 45,
    fiber: 0,
    ingredients: 'Carbonated Water, High Fructose Corn Syrup, Caramel Color, Phosphoric Acid, Natural Flavors, Caffeine',
    sweeteners: [{ name: 'High Fructose Corn Syrup', position: 2 }],
  },
  {
    upc: '049000028904',
    brand: 'Pepsi',
    name: 'Pepsi Cola',
    description: 'Carbonated soft drink',
    servingSize: '12 fl oz (355mL)',
    calories: 150,
    totalSugars: 41,
    addedSugars: 41,
    totalCarbs: 41,
    protein: 0,
    fat: 0,
    sodium: 30,
    fiber: 0,
    ingredients: 'Carbonated Water, High Fructose Corn Syrup, Caramel Color, Sugar, Phosphoric Acid, Caffeine, Citric Acid, Natural Flavor',
    sweeteners: [
      { name: 'High Fructose Corn Syrup', position: 2 },
      { name: 'Cane Sugar', position: 4 },
    ],
  },
  {
    upc: '012000814211',
    brand: 'Sprite',
    name: 'Sprite Lemon-Lime Soda',
    description: 'Lemon-lime flavored soft drink',
    servingSize: '12 fl oz',
    calories: 140,
    totalSugars: 38,
    addedSugars: 38,
    totalCarbs: 38,
    protein: 0,
    fat: 0,
    sodium: 65,
    fiber: 0,
    ingredients: 'Carbonated Water, High Fructose Corn Syrup, Citric Acid, Natural Flavors, Sodium Citrate, Sodium Benzoate',
    sweeteners: [{ name: 'High Fructose Corn Syrup', position: 2 }],
  },
  {
    upc: '012000814310',
    brand: 'Diet Coke',
    name: 'Diet Coke',
    description: 'Zero calorie cola',
    servingSize: '12 fl oz',
    calories: 0,
    totalSugars: 0,
    addedSugars: 0,
    totalCarbs: 0,
    protein: 0,
    fat: 0,
    sodium: 40,
    fiber: 0,
    ingredients: 'Carbonated Water, Caramel Color, Aspartame, Phosphoric Acid, Potassium Benzoate, Natural Flavors, Citric Acid, Caffeine',
    sweeteners: [{ name: 'Aspartame', position: 3 }],
  },
  {
    upc: '078000113204',
    brand: 'Gatorade',
    name: 'Gatorade Thirst Quencher - Lemon Lime',
    description: 'Sports drink',
    servingSize: '12 fl oz',
    calories: 80,
    totalSugars: 21,
    addedSugars: 21,
    totalCarbs: 21,
    protein: 0,
    fat: 0,
    sodium: 160,
    fiber: 0,
    ingredients: 'Water, Sugar, Dextrose, Citric Acid, Salt, Sodium Citrate, Monopotassium Phosphate, Natural Flavor, Yellow 5',
    sweeteners: [
      { name: 'Cane Sugar', position: 2 },
      { name: 'Dextrose', position: 3 },
    ],
  },
  {
    upc: '074175434120',
    brand: 'LaCroix',
    name: 'Sparkling Water - Lime',
    description: 'Naturally flavored sparkling water',
    servingSize: '12 fl oz (355mL)',
    calories: 0,
    totalSugars: 0,
    addedSugars: 0,
    totalCarbs: 0,
    protein: 0,
    fat: 0,
    sodium: 0,
    fiber: 0,
    ingredients: 'Carbonated Water, Natural Flavors',
    sweeteners: [],
  },

  // Dairy & Alternatives
  {
    upc: '070470002075',
    brand: 'Fage',
    name: 'Total 0% Greek Yogurt',
    description: 'Nonfat Greek yogurt',
    servingSize: '3/4 cup (170g)',
    calories: 90,
    totalSugars: 5,
    addedSugars: 0,
    totalCarbs: 6,
    protein: 18,
    fat: 0,
    sodium: 65,
    fiber: 0,
    ingredients: 'Grade A Pasteurized Skimmed Milk, Live Active Yogurt Cultures',
    sweeteners: [],
  },
  {
    upc: '036632026569',
    brand: 'Yoplait',
    name: 'Original Strawberry Yogurt',
    description: 'Low-fat strawberry yogurt',
    servingSize: '6 oz (170g)',
    calories: 150,
    totalSugars: 26,
    addedSugars: 18,
    totalCarbs: 31,
    protein: 5,
    fat: 2,
    sodium: 90,
    fiber: 0,
    ingredients: 'Cultured Grade A Low Fat Milk, Sugar, Strawberries, Modified Corn Starch, High Fructose Corn Syrup, Nonfat Milk, Kosher Gelatin, Citric Acid, Tricalcium Phosphate, Natural Flavor, Pectin, Colored with Carmine, Vitamin A Acetate, Vitamin D3',
    sweeteners: [
      { name: 'Cane Sugar', position: 2 },
      { name: 'High Fructose Corn Syrup', position: 5 },
    ],
  },
  {
    upc: '025293600294',
    brand: 'Silk',
    name: 'Unsweetened Almond Milk',
    description: 'Plant-based milk alternative',
    servingSize: '1 cup (240mL)',
    calories: 30,
    totalSugars: 0,
    addedSugars: 0,
    totalCarbs: 1,
    protein: 1,
    fat: 2.5,
    sodium: 170,
    fiber: 1,
    ingredients: 'Almondmilk (Filtered Water, Almonds), Calcium Carbonate, Sea Salt, Potassium Citrate, Sunflower Lecithin, Gellan Gum, Natural Flavors, Vitamin A Palmitate, Vitamin D2, D-Alpha-Tocopherol',
    sweeteners: [],
  },
  {
    upc: '041220685813',
    brand: 'Chobani',
    name: 'Vanilla Greek Yogurt',
    description: 'Low-fat Greek yogurt',
    servingSize: '5.3 oz (150g)',
    calories: 130,
    totalSugars: 14,
    addedSugars: 9,
    totalCarbs: 16,
    protein: 12,
    fat: 2.5,
    sodium: 60,
    fiber: 0,
    ingredients: 'Cultured Lowfat Milk, Cane Sugar, Water, Natural Flavors, Fruit Pectin, Guar Gum, Locust Bean Gum, Vanilla Extract',
    sweeteners: [{ name: 'Cane Sugar', position: 2 }],
  },

  // Breakfast & Cereals
  {
    upc: '038000291807',
    brand: 'General Mills',
    name: 'Cheerios',
    description: 'Toasted whole grain oat cereal',
    servingSize: '1 cup (28g)',
    calories: 100,
    totalSugars: 1,
    addedSugars: 1,
    totalCarbs: 20,
    protein: 3,
    fat: 2,
    sodium: 140,
    fiber: 3,
    ingredients: 'Whole Grain Oats, Modified Corn Starch, Sugar, Salt, Tripotassium Phosphate',
    sweeteners: [{ name: 'Cane Sugar', position: 3 }],
  },
  {
    upc: '038000045301',
    brand: 'General Mills',
    name: 'Honey Nut Cheerios',
    description: 'Sweetened whole grain oat cereal',
    servingSize: '3/4 cup (28g)',
    calories: 110,
    totalSugars: 9,
    addedSugars: 9,
    totalCarbs: 22,
    protein: 2,
    fat: 1.5,
    sodium: 140,
    fiber: 2,
    ingredients: 'Whole Grain Oats, Sugar, Modified Corn Starch, Honey, Brown Sugar Syrup, Salt, Tripotassium Phosphate, Canola and/or Rice Bran Oil, Natural Almond Flavor',
    sweeteners: [
      { name: 'Cane Sugar', position: 2 },
      { name: 'Honey', position: 4 },
      { name: 'Brown Sugar', position: 5 },
    ],
  },
  {
    upc: '052603051859',
    brand: 'Quaker',
    name: 'Steel Cut Oats',
    description: 'Whole grain oats',
    servingSize: '1/4 cup dry (40g)',
    calories: 150,
    totalSugars: 0,
    addedSugars: 0,
    totalCarbs: 27,
    protein: 5,
    fat: 2.5,
    sodium: 0,
    fiber: 4,
    ingredients: '100% Whole Grain Steel Cut Oats',
    sweeteners: [],
  },
  {
    upc: '030000010303',
    brand: 'Kellogg\'s',
    name: 'Frosted Flakes',
    description: 'Sweetened corn flakes cereal',
    servingSize: '3/4 cup (31g)',
    calories: 110,
    totalSugars: 10,
    addedSugars: 10,
    totalCarbs: 27,
    protein: 1,
    fat: 0,
    sodium: 140,
    fiber: 1,
    ingredients: 'Milled Corn, Sugar, Malt Flavor, High Fructose Corn Syrup, Salt',
    sweeteners: [
      { name: 'Cane Sugar', position: 2 },
      { name: 'High Fructose Corn Syrup', position: 4 },
    ],
  },

  // Snacks & Bars
  {
    upc: '016000119710',
    brand: 'Nature Valley',
    name: 'Crunchy Granola Bars - Oats and Honey',
    description: 'Granola bars',
    servingSize: '2 bars (42g)',
    calories: 190,
    totalSugars: 11,
    addedSugars: 10,
    totalCarbs: 29,
    protein: 4,
    fat: 6,
    sodium: 160,
    fiber: 2,
    ingredients: 'Whole Grain Oats, Sugar, Canola Oil, Rice Flour, Honey, Brown Sugar Syrup, Salt, Baking Soda, Soy Lecithin, Natural Flavor',
    sweeteners: [
      { name: 'Cane Sugar', position: 2 },
      { name: 'Honey', position: 5 },
      { name: 'Brown Sugar', position: 6 },
    ],
  },
  {
    upc: '722252100702',
    brand: 'KIND',
    name: 'Dark Chocolate Nuts & Sea Salt',
    description: 'Nut bar',
    servingSize: '1 bar (40g)',
    calories: 200,
    totalSugars: 5,
    addedSugars: 3,
    totalCarbs: 16,
    protein: 6,
    fat: 16,
    sodium: 125,
    fiber: 7,
    ingredients: 'Almonds, Peanuts, Honey, Palm Kernel Oil, Sugar, Glucose Syrup, Crisp Rice, Cocoa, Sea Salt, Soy Lecithin, Natural Flavor',
    sweeteners: [
      { name: 'Honey', position: 3 },
      { name: 'Cane Sugar', position: 5 },
    ],
  },
  {
    upc: '028400047647',
    brand: 'Cheez-It',
    name: 'Original Crackers',
    description: 'Cheese crackers',
    servingSize: '27 crackers (30g)',
    calories: 150,
    totalSugars: 0,
    addedSugars: 0,
    totalCarbs: 17,
    protein: 3,
    fat: 8,
    sodium: 230,
    fiber: 1,
    ingredients: 'Enriched Flour, Vegetable Oil, Cheese, Salt, Paprika, Yeast, Paprika Extract Color, Soy Lecithin',
    sweeteners: [],
  },

  // Spreads & Condiments
  {
    upc: '085239012598',
    brand: 'Justin\'s',
    name: 'Classic Almond Butter',
    description: 'Natural almond butter',
    servingSize: '2 Tbsp (32g)',
    calories: 190,
    totalSugars: 2,
    addedSugars: 0,
    totalCarbs: 7,
    protein: 7,
    fat: 16,
    sodium: 0,
    fiber: 3,
    ingredients: 'Dry Roasted Almonds, Palm Oil',
    sweeteners: [],
  },
  {
    upc: '051500255339',
    brand: 'Jif',
    name: 'Creamy Peanut Butter',
    description: 'Peanut butter spread',
    servingSize: '2 Tbsp (32g)',
    calories: 190,
    totalSugars: 3,
    addedSugars: 2,
    totalCarbs: 8,
    protein: 7,
    fat: 16,
    sodium: 140,
    fiber: 2,
    ingredients: 'Roasted Peanuts, Sugar, Molasses, Fully Hydrogenated Vegetable Oils, Mono And Diglycerides, Salt',
    sweeteners: [
      { name: 'Cane Sugar', position: 2 },
      { name: 'Molasses', position: 3 },
    ],
  },
  {
    upc: '041220915224',
    brand: 'Smucker\'s',
    name: 'Strawberry Jam',
    description: 'Fruit spread',
    servingSize: '1 Tbsp (20g)',
    calories: 50,
    totalSugars: 12,
    addedSugars: 10,
    totalCarbs: 13,
    protein: 0,
    fat: 0,
    sodium: 0,
    fiber: 0,
    ingredients: 'Strawberries, High Fructose Corn Syrup, Corn Syrup, Sugar, Fruit Pectin, Citric Acid',
    sweeteners: [
      { name: 'High Fructose Corn Syrup', position: 2 },
      { name: 'Cane Sugar', position: 4 },
    ],
  },
  {
    upc: '041130006098',
    brand: 'Heinz',
    name: 'Tomato Ketchup',
    description: 'Tomato condiment',
    servingSize: '1 Tbsp (17g)',
    calories: 20,
    totalSugars: 4,
    addedSugars: 4,
    totalCarbs: 5,
    protein: 0,
    fat: 0,
    sodium: 160,
    fiber: 0,
    ingredients: 'Tomato Concentrate, Distilled Vinegar, High Fructose Corn Syrup, Corn Syrup, Salt, Spice, Onion Powder, Natural Flavoring',
    sweeteners: [{ name: 'High Fructose Corn Syrup', position: 3 }],
  },

  // Bread & Bakery
  {
    upc: '041303002230',
    brand: 'Dave\'s Killer Bread',
    name: '21 Whole Grains and Seeds',
    description: 'Organic whole grain bread',
    servingSize: '1 slice (48g)',
    calories: 120,
    totalSugars: 5,
    addedSugars: 3,
    totalCarbs: 22,
    protein: 5,
    fat: 1.5,
    sodium: 170,
    fiber: 5,
    ingredients: 'Organic Whole Wheat, Water, Organic Cane Sugar, Organic Cracked Whole Wheat, Organic Sunflower Seeds, Organic Oats, Contains 2% or less of: Organic Flax Seeds, Organic Sesame Seeds, Organic Rye, Organic Triticale, Organic Pumpkin Seeds, Organic Barley, Organic Spelt, Organic Millet, Sea Salt, Organic Wheat Gluten, Cultured Wheat Flour, Organic Vinegar, Organic Molasses, Organic Cornmeal, Organic Rolled Oats, Yeast',
    sweeteners: [
      { name: 'Cane Sugar', position: 3 },
      { name: 'Molasses', position: 21 },
    ],
  },
  {
    upc: '007271400116',
    brand: 'Wonder Bread',
    name: 'Classic White Bread',
    description: 'Enriched white bread',
    servingSize: '1 slice (28g)',
    calories: 70,
    totalSugars: 2,
    addedSugars: 2,
    totalCarbs: 13,
    protein: 2,
    fat: 1,
    sodium: 115,
    fiber: 0,
    ingredients: 'Enriched Flour, Water, High Fructose Corn Syrup, Wheat Gluten, Yeast, Contains 2% or Less: Soybean Oil, Salt, Calcium Sulfate, Vinegar, Dough Conditioners',
    sweeteners: [{ name: 'High Fructose Corn Syrup', position: 3 }],
  },

  // Chocolate & Candy
  {
    upc: '041190468492',
    brand: 'Lindt',
    name: 'Excellence 85% Cocoa Dark Chocolate',
    description: 'Premium dark chocolate',
    servingSize: '4 squares (40g)',
    calories: 230,
    totalSugars: 7,
    addedSugars: 6,
    totalCarbs: 14,
    protein: 4,
    fat: 19,
    sodium: 0,
    fiber: 6,
    ingredients: 'Chocolate, Cocoa Butter, Cocoa Powder Processed with Alkali, Sugar, Bourbon Vanilla Beans',
    sweeteners: [{ name: 'Cane Sugar', position: 4 }],
  },
  {
    upc: '034000002306',
    brand: 'Hershey\'s',
    name: 'Milk Chocolate Bar',
    description: 'Milk chocolate',
    servingSize: '1 bar (43g)',
    calories: 220,
    totalSugars: 24,
    addedSugars: 24,
    totalCarbs: 26,
    protein: 3,
    fat: 13,
    sodium: 35,
    fiber: 1,
    ingredients: 'Milk Chocolate (Sugar, Milk, Chocolate, Cocoa Butter, Lactose, Milk Fat, Soy Lecithin, PGPR, Natural Flavor)',
    sweeteners: [{ name: 'Cane Sugar', position: 1 }],
  },
  {
    upc: '040000518624',
    brand: 'M&M\'s',
    name: 'Milk Chocolate Candies',
    description: 'Chocolate candy',
    servingSize: '1 package (47.9g)',
    calories: 240,
    totalSugars: 30,
    addedSugars: 30,
    totalCarbs: 34,
    protein: 2,
    fat: 10,
    sodium: 30,
    fiber: 1,
    ingredients: 'Milk Chocolate (Sugar, Chocolate, Skim Milk, Cocoa Butter, Lactose, Milkfat, Soy Lecithin, Salt, Natural Flavor), Sugar, Cornstarch, Less than 1% - Corn Syrup, Dextrin, Coloring, Carnauba Wax, Gum Acacia',
    sweeteners: [
      { name: 'Cane Sugar', position: 1 },
      { name: 'Cane Sugar', position: 8 },
    ],
  },

  // Frozen & Ice Cream
  {
    upc: '074570050840',
    brand: 'Ben & Jerry\'s',
    name: 'Half Baked Ice Cream',
    description: 'Chocolate & vanilla ice cream with brownies & cookie dough',
    servingSize: '2/3 cup (101g)',
    calories: 280,
    totalSugars: 26,
    addedSugars: 23,
    totalCarbs: 34,
    protein: 4,
    fat: 14,
    sodium: 65,
    fiber: 1,
    ingredients: 'Cream, Skim Milk, Liquid Sugar (Sugar, Water), Water, Sugar, Wheat Flour, Brown Sugar, Cocoa Processed With Alkali, Egg Yolks, Butter, Chocolate, Soybean Oil, Corn Syrup, Palm Oil, Vanilla Extract, Salt, Soy Lecithin, Baking Soda, Natural Flavor, Guar Gum, Carrageenan',
    sweeteners: [
      { name: 'Cane Sugar', position: 3 },
      { name: 'Cane Sugar', position: 5 },
      { name: 'Brown Sugar', position: 7 },
    ],
  },
  {
    upc: '074570531028',
    brand: 'Halo Top',
    name: 'Vanilla Bean Light Ice Cream',
    description: 'Low calorie ice cream',
    servingSize: '2/3 cup (89g)',
    calories: 90,
    totalSugars: 6,
    addedSugars: 4,
    totalCarbs: 16,
    protein: 5,
    fat: 3,
    sodium: 100,
    fiber: 4,
    ingredients: 'Skim Milk, Erythritol, Cream, Prebiotic Fiber, Milk Protein Concentrate, Organic Cane Sugar, High Fat Cocoa, Vegetable Glycerin, Sea Salt, Natural Flavor, Organic Carob Gum, Organic Guar Gum, Organic Stevia Leaf Extract',
    sweeteners: [
      { name: 'Erythritol', position: 2 },
      { name: 'Cane Sugar', position: 6 },
      { name: 'Stevia', position: 14 },
    ],
  },

  // Juices
  {
    upc: '025000053382',
    brand: 'Minute Maid',
    name: 'Original Orange Juice',
    description: '100% orange juice',
    servingSize: '8 fl oz (240mL)',
    calories: 110,
    totalSugars: 22,
    addedSugars: 0,
    totalCarbs: 26,
    protein: 2,
    fat: 0,
    sodium: 0,
    fiber: 0,
    ingredients: '100% Pure Squeezed Pasteurized Orange Juice',
    sweeteners: [],
  },
  {
    upc: '051000127884',
    brand: 'Tropicana',
    name: 'Orange Juice - No Pulp',
    description: '100% orange juice',
    servingSize: '8 fl oz',
    calories: 110,
    totalSugars: 22,
    addedSugars: 0,
    totalCarbs: 26,
    protein: 2,
    fat: 0,
    sodium: 0,
    fiber: 0,
    ingredients: '100% Pure Orange Juice',
    sweeteners: [],
  },
  {
    upc: '014800005745',
    brand: 'Ocean Spray',
    name: 'Cranberry Juice Cocktail',
    description: 'Cranberry juice drink',
    servingSize: '8 fl oz',
    calories: 110,
    totalSugars: 27,
    addedSugars: 24,
    totalCarbs: 28,
    protein: 0,
    fat: 0,
    sodium: 5,
    fiber: 0,
    ingredients: 'Filtered Water, Cranberry Juice Concentrate, High Fructose Corn Syrup, Ascorbic Acid (Vitamin C)',
    sweeteners: [{ name: 'High Fructose Corn Syrup', position: 3 }],
  },

  // Cookies & Baked Goods
  {
    upc: '044000032302',
    brand: 'Oreo',
    name: 'Original Sandwich Cookies',
    description: 'Chocolate sandwich cookies',
    servingSize: '3 cookies (34g)',
    calories: 160,
    totalSugars: 14,
    addedSugars: 13,
    totalCarbs: 25,
    protein: 1,
    fat: 7,
    sodium: 135,
    fiber: 1,
    ingredients: 'Unbleached Enriched Flour, Sugar, Palm and/or Canola Oil, Cocoa (Processed With Alkali), High Fructose Corn Syrup, Leavening (Baking Soda and/or Calcium Phosphate), Cornstarch, Salt, Soy Lecithin, Vanillin, Chocolate',
    sweeteners: [
      { name: 'Cane Sugar', position: 2 },
      { name: 'High Fructose Corn Syrup', position: 5 },
    ],
  },

  // Tea & Coffee
  {
    upc: '077567510310',
    brand: 'Arizona',
    name: 'Green Tea with Ginseng and Honey',
    description: 'Sweetened iced tea',
    servingSize: '8 fl oz',
    calories: 70,
    totalSugars: 17,
    addedSugars: 17,
    totalCarbs: 18,
    protein: 0,
    fat: 0,
    sodium: 15,
    fiber: 0,
    ingredients: 'Premium Brewed Green Tea Using Filtered Water, High Fructose Corn Syrup, Honey, Citric Acid, Natural Flavors, Ginseng Extract, Ascorbic Acid (Vitamin C)',
    sweeteners: [
      { name: 'High Fructose Corn Syrup', position: 2 },
      { name: 'Honey', position: 3 },
    ],
  },
]

async function main() {
  console.log('🌱 Seeding extended product database...')

  let created = 0
  let updated = 0
  let sweetenersLinked = 0

  for (const productData of products) {
    const { sweeteners: sweetenerData, ...productFields } = productData

    // Create or update product
    const product = await prisma.product.upsert({
      where: { upc: productData.upc },
      update: productFields,
      create: productFields,
    })

    if (product.createdAt === product.updatedAt) {
      created++
    } else {
      updated++
    }

    // Link sweeteners
    for (const sweetenerInfo of sweetenerData) {
      const sweetener = await prisma.sweetener.findUnique({
        where: { name: sweetenerInfo.name },
      })

      if (sweetener) {
        await prisma.productSweetener.upsert({
          where: {
            productId_sweetenerId: {
              productId: product.id,
              sweetenerId: sweetener.id,
            },
          },
          update: {
            position: sweetenerInfo.position,
          },
          create: {
            productId: product.id,
            sweetenerId: sweetener.id,
            position: sweetenerInfo.position,
          },
        })
        sweetenersLinked++
      }
    }

    console.log(`  ✓ ${product.brand} - ${product.name}`)
  }

  console.log(`\n✅ Extended product seeding complete!`)
  console.log(`   Created: ${created} products`)
  console.log(`   Updated: ${updated} products`)
  console.log(`   Sweeteners linked: ${sweetenersLinked}`)
  console.log(`   Total: ${products.length} products`)
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
